/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package routeensapl;

import javax.swing.JOptionPane;

/**
 *
 * @author adild
 */
public class dashboard extends javax.swing.JFrame {

    /**
     * Creates new form homePage
     */
    public dashboard() {
        initComponents();
        
    }
    
    public dashboard(String _username) {
        initComponents();
        lblWelcome.setText("Welcome, " + _username);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tab4 = new javax.swing.JButton();
        tab3 = new javax.swing.JButton();
        tab2 = new javax.swing.JButton();
        tab1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 10)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("check progress");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 90, 20));

        jButton1.setText("click");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 70, 30));

        tab4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPackage/tabDefault.png"))); // NOI18N
        tab4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab4ActionPerformed(evt);
            }
        });
        getContentPane().add(tab4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 140, 140, 280));

        tab3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPackage/tabDefault.png"))); // NOI18N
        tab3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab3ActionPerformed(evt);
            }
        });
        getContentPane().add(tab3, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 140, 140, 280));

        tab2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPackage/tabDefault.png"))); // NOI18N
        tab2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab2ActionPerformed(evt);
            }
        });
        getContentPane().add(tab2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 140, 280));

        tab1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPackage/tabDefault.png"))); // NOI18N
        tab1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tab1ActionPerformed(evt);
            }
        });
        getContentPane().add(tab1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 140, 280));

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        jLabel3.setText("Start Your Program");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 90, -1, -1));

        lblWelcome.setFont(new java.awt.Font("Showcard Gothic", 0, 24)); // NOI18N
        lblWelcome.setText("Welcome,");
        getContentPane().add(lblWelcome, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPackage/dashboardDef (1).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 840, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tab1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab1ActionPerformed
        // TODO add your handling code here:
        frame5 il = new frame5();
                il.setLocationRelativeTo(null);
                il.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_tab1ActionPerformed

    private void tab2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tab2ActionPerformed

    private void tab3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tab3ActionPerformed

    private void tab4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tab4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tab4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
statistic st = new statistic();
                st.setLocationRelativeTo(null);
                st.setVisible(true);
                this.setVisible(false);        // TODO add your handling code here:
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    
     private void lblWelcomeActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                dashboard dashboard = new dashboard();
                dashboard.setLocationRelativeTo(null);
                dashboard.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JButton tab1;
    private javax.swing.JButton tab2;
    private javax.swing.JButton tab3;
    private javax.swing.JButton tab4;
    // End of variables declaration//GEN-END:variables
}
