/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package routeensapl;

/**
 *
 * @author adild
 */
public class frame5 extends javax.swing.JFrame {

    /**
     * Creates new form frame5
     */
    public frame5() {
        initComponents();
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox36 = new javax.swing.JCheckBox();
        jCheckBox35 = new javax.swing.JCheckBox();
        jCheckBox34 = new javax.swing.JCheckBox();
        jCheckBox33 = new javax.swing.JCheckBox();
        jCheckBox32 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        pilihHabit = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        txtHbt5 = new javax.swing.JLabel();
        txtHbt4 = new javax.swing.JLabel();
        txtHbt3 = new javax.swing.JLabel();
        txtHbt2 = new javax.swing.JLabel();
        txtHbt1 = new javax.swing.JLabel();
        habitnya = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtInput = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jCheckBox36, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 330, 30, 30));
        getContentPane().add(jCheckBox35, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 299, 30, 30));
        getContentPane().add(jCheckBox34, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 30, -1));
        getContentPane().add(jCheckBox33, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 240, 30, -1));
        getContentPane().add(jCheckBox32, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 210, 30, -1));

        jCheckBox31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox31ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox31, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 240, 30, -1));
        getContentPane().add(jCheckBox30, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 270, 30, -1));
        getContentPane().add(jCheckBox29, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 310, 30, -1));
        getContentPane().add(jCheckBox28, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 340, 30, -1));
        getContentPane().add(jCheckBox27, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 30, -1));
        getContentPane().add(jCheckBox26, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 210, 30, -1));
        getContentPane().add(jCheckBox25, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 330, -1, 30));
        getContentPane().add(jCheckBox24, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 300, -1, 30));
        getContentPane().add(jCheckBox23, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 270, -1, -1));
        getContentPane().add(jCheckBox22, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 240, -1, -1));
        getContentPane().add(jCheckBox21, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, -1, -1));

        jCheckBox20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox20ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox20, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 340, -1, -1));
        getContentPane().add(jCheckBox19, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 300, -1, 30));

        jCheckBox18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox18ActionPerformed(evt);
            }
        });
        getContentPane().add(jCheckBox18, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));
        getContentPane().add(jCheckBox17, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 240, -1, -1));
        getContentPane().add(jCheckBox16, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, -1, -1));
        getContentPane().add(jCheckBox15, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 330, -1, 30));
        getContentPane().add(jCheckBox14, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 299, -1, 30));
        getContentPane().add(jCheckBox13, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 270, -1, -1));
        getContentPane().add(jCheckBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 240, -1, -1));
        getContentPane().add(jCheckBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));
        getContentPane().add(jCheckBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 340, -1, -1));
        getContentPane().add(jCheckBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, -1, -1));
        getContentPane().add(jCheckBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 270, -1, -1));
        getContentPane().add(jCheckBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 240, -1, -1));
        getContentPane().add(jCheckBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 210, -1, -1));
        getContentPane().add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 340, -1, -1));
        getContentPane().add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 299, -1, 30));
        getContentPane().add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 270, -1, -1));
        getContentPane().add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, -1, -1));
        getContentPane().add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        pilihHabit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "habit 1", "habit 2", "habit 3", "habit 4", "habit 5", " " }));
        pilihHabit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilihHabitActionPerformed(evt);
            }
        });
        getContentPane().add(pilihHabit, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, -1, -1));

        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(345, 383, 170, 40));

        txtHbt5.setText("habit 5");
        txtHbt5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHbt5MouseClicked(evt);
            }
        });
        getContentPane().add(txtHbt5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 340, -1, -1));

        txtHbt4.setText("habit 4");
        txtHbt4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHbt4MouseClicked(evt);
            }
        });
        getContentPane().add(txtHbt4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, -1, -1));

        txtHbt3.setText("habit 3");
        txtHbt3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHbt3MouseClicked(evt);
            }
        });
        getContentPane().add(txtHbt3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, -1, -1));

        txtHbt2.setText("habit 2");
        txtHbt2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHbt2MouseClicked(evt);
            }
        });
        getContentPane().add(txtHbt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        txtHbt1.setText("habit 1");
        txtHbt1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtHbt1MouseClicked(evt);
            }
        });
        getContentPane().add(txtHbt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        habitnya.setText("habit 1");
        getContentPane().add(habitnya, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 100, -1, -1));

        jButton2.setText("choose habit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, -1, -1));

        jButton1.setText("enter");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 130, -1, 30));

        txtInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtInputActionPerformed(evt);
            }
        });
        getContentPane().add(txtInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 100, 160, -1));

        jLabel9.setText("Day 7");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 170, -1, -1));

        jLabel8.setText("Day 6");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, -1, -1));

        jLabel7.setText("Day 5");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 170, -1, -1));

        jLabel6.setText("Day 4");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 170, -1, -1));

        jLabel5.setText("Day 3");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, -1, -1));

        jLabel4.setText("Day 2");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, -1, -1));

        jLabel3.setText("Day 1");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, -1, -1));

        jLabel2.setText("Aa | Habits");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconPackage/wpp tabel .jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 441));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtInputActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_txtInputActionPerformed

    private void jCheckBox18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox18ActionPerformed

    private void jCheckBox20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox20ActionPerformed

    private void jCheckBox31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox31ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       switch (habitnya.getText()) {
           case "habit 1":
            txtHbt1.setText(txtInput.getText());
            break;
            case "habit 2":
            txtHbt2.setText(txtInput.getText());
            break;
             case "habit 3":
            txtHbt3.setText(txtInput.getText());
            break;
             case "habit 4":
            txtHbt4.setText(txtInput.getText());
            break;
             case "habit 5":
            txtHbt5.setText(txtInput.getText());
            break;
       }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtHbt1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHbt1MouseClicked
        // TODO add your handling code here:
        String input1 = txtInput.getText();
        txtHbt1.setText("" + input1);
    }//GEN-LAST:event_txtHbt1MouseClicked

    private void txtHbt2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHbt2MouseClicked
        // TODO add your handling code here:
        String input2 =txtInput.getText();
        txtHbt2.setText("" + input2);
    }//GEN-LAST:event_txtHbt2MouseClicked

    private void txtHbt3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHbt3MouseClicked
        // TODO add your handling code here:
        String input3 =txtInput.getText();
        txtHbt3.setText("" + input3);
    }//GEN-LAST:event_txtHbt3MouseClicked

    private void txtHbt4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHbt4MouseClicked
        // TODO add your handling code here:
        String input4 =txtInput.getText();
        txtHbt4.setText("" + input4);
    }//GEN-LAST:event_txtHbt4MouseClicked

    private void txtHbt5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtHbt5MouseClicked
        // TODO add your handling code here:
        String input5 =txtInput.getText();
        txtHbt5.setText("" + input5);
    }//GEN-LAST:event_txtHbt5MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        habitnya.setText(pilihHabit.getSelectedItem().toString());
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void pilihHabitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilihHabitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pilihHabitActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        dashboard dB = new dashboard();
                dB.setLocationRelativeTo(null);
               dB.setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel habitnya;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox33;
    private javax.swing.JCheckBox jCheckBox34;
    private javax.swing.JCheckBox jCheckBox35;
    private javax.swing.JCheckBox jCheckBox36;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JComboBox<String> pilihHabit;
    private javax.swing.JLabel txtHbt1;
    private javax.swing.JLabel txtHbt2;
    private javax.swing.JLabel txtHbt3;
    private javax.swing.JLabel txtHbt4;
    private javax.swing.JLabel txtHbt5;
    private javax.swing.JTextField txtInput;
    // End of variables declaration//GEN-END:variables
}
